// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tgwpakovvxucsuezrnfc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRnd3Bha292dnh1Y3N1ZXpybmZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMDYyNzQsImV4cCI6MjA2NDg4MjI3NH0.4yu1TJUwMQhIvorYrU-C6q6pTyrhI3XKzMZbbJ3QijQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);